### ISSUE TITLE
source taraball contains dead links

### ISSUE THREAD

**Issue by jgmbenoit** [flatsurf/e-antic#189] opened 2021-07-03 11:52 UTC
It appears that the source tarball contains dead links in libeantic/upstream/patched : please consider to provide the original sources not the their links.

**Comment by saraedum** [comment] 2021-07-05 22:47
@jgmbenoit sorry, I am not sure which tarball you are referring to. The one on the releases page here called `e-antic-1.0.1.tar.gz` does not seem to contain any symlinks. Could you clarify?

**Comment by jgmbenoit** [comment] 2021-07-06 05:28
At the [release page](https://github.com/flatsurf/e-antic/releases/tag/1.0.1), the [explicit source ball ](https://github.com/flatsurf/e-antic/releases/download/1.0.1/e-antic-1.0.1.tar.gz) contains indeed no orphan links. However, at the same page, the [Source Code tarball](https://github.com/flatsurf/e-antic/archive/refs/tags/1.0.1.tar.gz) contains orphan links in libeantic/upstream/patched .

**Comment by saraedum** [comment] 2021-07-06 09:42
I see. The source code tarball is created automatically by github from the release tag. I don't think I can edit it. Since it does not pull in submodules, it is missing lots of files actually.
I don't think we can do anything about it unfortunately, https://github.community/t/create-release-that-contains-submodule/1329.

I will close this issue since github is broken by design here it appears. I am happy to reopen this one if I missed something of course.

**Comment by jgmbenoit** [comment] 2022-02-19 16:51
Okay, I have to play with the [explicit source ball](https://github.com/flatsurf/e-antic/releases/download/1.1.0/e-antic-1.1.0.tar.gz).
I have just noticed that it does not contain the `doc` material. Can you  provide it  ?

**Comment by jgmbenoit** [comment] 2022-02-20 15:34
It also appears that the map files are actually missing in the  [explicit source ball](https://github.com/flatsurf/e-antic/releases/download/1.1.0/e-antic-1.1.0.tar.gz).

**Comment by saraedum** [comment] 2022-02-24 23:40
I pushed the `doc/` problem out to #231.

The `doc/` is probably not terribly useful for Debian yet (if that's the use case) since you need an unreleased version of standardese to be actually able to build it.

**Comment by saraedum** [comment] 2022-02-24 23:41
The missing version scripts should be fixed in #232.

**Closed** 2022-02-25 00:03 UTC
